---

- hosts: kube
  become: yes

  
  

  tasks:
    - name: apt-get update
      apt: update_cache=yes
      
    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        
    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: Add Docker apt repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
        state: present
        update_cache: yes
        
    - name: Install Docker Engine - Community and containerd
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
        
        
        
        
    - name: Add Kubernetes official GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
        
    - name: Add Kubernetes apt repository
      apt_repository:
        repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
        state: present
        update_cache: yes
        
    - name: Installing kubeadm, kubelet and kubectl
      apt:
        pkg:
        - kubelet
        - kubeadm
        - kubectl
